# Generated by Django 3.2.4 on 2021-06-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_text',
            field=models.TextField(verbose_name='Description'),
        ),
    ]
